setw -g mouse off

set -g renumber-windows on
set -g visual-bell off
set -g visual-activity off
set -sg escape-time 0
set -g history-limit 2000
set -g buffer-limit 20
set -g status-keys vi

setw -g mode-keys vi
setw -g xterm-keys on

# Start index of window/pane with 1
set -g base-index 1
setw -g pane-base-index 1

# Rebind C-b -> C-a
unbind C-b
set -g prefix C-a
bind-key C-a last-window
bind a send-prefix

# Split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

# Reload tmux config
bind r source-file ~/.tmux.conf \; display "config reloaded"

# --------------------------------------
# Colors
# --------------------------------------

set -g @base '#35353E'
set -g @surface '#4C5E82'
set -g @text '#DCD7BA'
set -g @muted '#848170'

set -g @color0 '#090618'
set -g @color1 '#C34043'
set -g @color2 '#76946A'
set -g @color3 '#C0A36E'
set -g @color4 '#7E9CD8'
set -g @color5 '#957FB8'
set -g @color6 '#6A9589'
set -g @color7 '#C8C093'
set -g @color8 '#727169'
set -g @color9 '#E82424'
set -g @color10 '#98BB6C'
set -g @color11 '#E6C384'
set -g @color12 '#7FB4CA'
set -g @color13 '#938AA9'
set -g @color14 '#7AA89F'
set -g @color15 '#DCD7BA'

# --------------------------------------
# Status line
# --------------------------------------

# Set parent terminal title to reflect current window in tmux session
set -g set-titles on
set -g set-titles-string "#I:#W"

# Status bar
set-option -g status on
set-option -g status-position bottom
set-option -g status-style 'none,fg=#{@muted},bg=default'
# Status bar left
set-option -g status-left-length 100
set-option -g status-left-style 'bg=default'
set-option -g status-left ''
# Status bar right
set-option -g status-right-length 100
set-option -g status-right-style none
# BSD and GNU hostname commands generate different default output. Adapt it to your preference.
set-option -g status-right '#[fg=#{@surface},bg=default] #h'
# Window bars
set-option -g status-justify left
set-option -g window-status-style none
# Turn monitor-activity on to display activity glyph
set-option -g window-status-format '#[fg=#{@base},bg=default]#[fg=#{@muted},bg=#{@base}] #I: #W #[fg=#{@base},bg=default]'
# Window bars
set-option -g window-status-current-style none
set-option -g window-status-current-format '#[fg=#{@surface},bg=default]#[fg=#{@text},bg=#{@surface}] #I: #W #[fg=#{@surface},bg=default]'
set-option -g window-status-activity-style 'none,fg=#{@muted},bg=#{@base}'
set-option -g window-status-separator ''
# Panes
set-option -g pane-active-border-style 'fg=#{@color13}'
set-option -g pane-border-style 'fg=#{@base}'
# Messages
set-option -g message-style 'none,fg=#{@muted},bg=#{@base}'
set-option -g message-command-style 'none,fg=#{@muted},bg=#{@base}'
